Update odoo_cicd.yml

diff --git a/.github/workflows/odoo_cicd.yml b/.github/workflows/odoo_cicd.yml
--- a/.github/workflows/odoo_cicd.yml
+++ b/.github/workflows/odoo_cicd.yml
@@ -26,7 +26,13 @@ jobs:
       - name: Run pylint-odoo
         run: |
           pylint --load-plugins=pylint_odoo web_monitor/ | tee pylint.log
-          grep -q ":\sE" pylint.log && exit 1 || exit 0
+          if grep -q ":\sE" pylint.log; then
+            echo "Lint errors (E*) found!"
+            exit 1
+          else
+            echo "No E-level errors found."
+            exit 0
+          fi
   
   deploy:
     name: Deploy to Odoo Server
